# Generated by Django 2.0.8 on 2018-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0006_auto_20181114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislodgedates',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
