# Generated by Django 2.0.8 on 2018-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0008_profile_initial_dislodge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_litres',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
