# Generated by Django 2.0.8 on 2018-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0009_profile_num_of_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TippingPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lat_lng', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
