# Generated by Django 2.0.9 on 2018-11-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0012_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shitty.Driver'),
        ),
        migrations.AddField(
            model_name='request',
            name='disludged',
            field=models.BooleanField(default=False),
        ),
    ]
