# Generated by Django 2.0.9 on 2018-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0013_auto_20181117_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
