# Generated by Django 2.0.9 on 2018-11-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0014_request_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
