# Generated by Django 2.0.9 on 2018-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0016_driver_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='bpo/'),
        ),
    ]
