# Generated by Django 2.0.9 on 2018-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0017_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
