# Generated by Django 2.0.9 on 2018-11-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0018_request_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislodgedates',
            name='requested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shitty.Profile'),
        ),
    ]
