# Generated by Django 2.0.9 on 2018-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0020_biorequest_biotypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='biorequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biorequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
