# Generated by Django 2.0.9 on 2018-11-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0021_auto_20181119_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='biorequest',
            name='issue_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
