# Generated by Django 2.0.9 on 2018-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0022_biorequest_issue_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='biorequest',
            name='price_charges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
