# Generated by Django 2.0.9 on 2018-11-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0023_biorequest_price_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildToilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('done', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('accepted_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shitty.Driver')),
                ('requested_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shitty.Profile')),
            ],
        ),
    ]
