# Generated by Django 2.0.9 on 2018-11-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shitty', '0025_buildtoilet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval1', models.CharField(blank=True, max_length=100, null=True)),
                ('eval2', models.CharField(blank=True, max_length=100, null=True)),
                ('eval3', models.CharField(blank=True, max_length=100, null=True)),
                ('eval4', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shitty.Driver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
