# Generated by Django 2.0.9 on 2018-11-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shitty', '0026_evalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalform',
            name='driver',
        ),
    ]
